import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/app/providers";
import { inter, walsheim, dmSans, manrope, degular } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Ambitful AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" translate="no">
      <body
        className={`${degular.variable} ${walsheim.variable} ${inter.className} ${dmSans.variable} ${manrope.variable} antialiased`}
      >
        <Providers>{children}</Providers>
        <div id="modal"></div>
      </body>
    </html>
  );
}
