import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

const degular = localFont({
  src: [
    {
      path: "../public/fonts/fonnts.com-DegularDemo-Thin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/fonnts.com-DegularDemo-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/fonnts.com-DegularDemo-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/fonnts.com-DegularDemo-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/fonnts.com-DegularDemo-Semibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/fonnts.com-DegularDemo-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/fonnts.com-DegularDemo-Black.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/fonnts.com-DegularDemo-Italic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/fonnts.com-DegularDemo-MediumItalic.otf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../public/fonts/fonnts.com-DegularDemo-BoldItalic.otf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-degular",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ambitful AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${degular.variable} ${inter.className} antialiased`}>
        <>{children}</>
      </body>
    </html>
  );
}
